name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/
        env:
          PYTHONPATH: ${{ github.workspace }}/src

  train_quantize:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Quantize model
        run: python src/quantize.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: |
            model.joblib
            quant_params.joblib
            unquant_params.joblib

  docker_build_test:
    needs: train_quantize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pipeline-artifacts
          path: artifacts/

      - name: Build Docker image
        run: docker build -t mlops-linear .

      - name: Test Docker container
        run: docker run mlops-linear
